---
basename: bogus
common_name: bogus.example
subject_alt_names: []

base_directory: /etc/ssl/ansible

self_sign: False

csr_path: "{{ base_directory }}/certs/{{ basename }}.csr"
certificate_path: "{{ base_directory }}/certs/{{ basename }}.pem"
fullchain_path: "{{ base_directory }}/certs/{{ basename }}.fullchain.pem"
privatekey_path: "{{ base_directory }}/private/{{ basename }}.key"

nginx_snippet_path: "/etc/nginx/snippets/letsencrypt-{{ basename }}.conf"

letsencrypt_account_key: "{{ base_directory }}/private/letsencrypt_account.key"
letsencrypt_account_email: foo@dbar.org

letsencrypt_agreement: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
letsencrypt_acme_directory: https://acme-v01.api.letsencrypt.org/directory

letsencrypt_chain_path: "{{ base_directory }}/certs/letsencrypt.chain.pem"

letsencrypt_challenge_mode: http-01
letsencrypt_well_known_dir: /var/www/well-known
letsencrypt_do_nginx_vhost: False

