---
- name: install packages
  apt: pkg={{ item }}
  with_items:
  - git
  - ffmpeg
  - libmojolicious-perl
  - libdbd-pg-perl
  - libglib-perl
  - gir1.2-gstreamer-1.0
  - libglib-object-introspection-perl
  - gir1.2-gst-plugins-base-1.0
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-ugly
  - gstreamer1.0-plugins-good
  - bs1770gain
  - inkscape

- name: clone git repository
  become: true
  become_user: videoteam
  git:
    repo: https://github.com/yoe/sreview
    dest: /home/videoteam/sreview

- name: create working directory
  file:
    path: /home/videoteam/tmp
    state: directory
    owner: videoteam
    group: videoteam

- name: write config file
  when: sreviewdbpw is defined
  template:
    dest: /home/videoteam/sreview/scripts/config.pl
    owner: videoteam
    group: videoteam
    mode: 0600
    src: config.pl.j2
    force: no
