---
- name: install packages
  apt:
    pkg: sreview-encoder

- name: create working directory
  file:
    path: /var/lib/sreview/tmp
    state: directory
    owner: sreview
    group: sreview

- name: write config file
  when: sreview.dbpw is defined
  template:
    dest: /etc/sreview/config.pm
    owner: root
    group: sreview
    mode: 0640
    src: config.pm.j2
    force: no

- name: copy pre/postroll files
  copy:
    src: "{{ item.file }}"
    dest: "/var/lib/sreview/{{ item.name }}.svg"
    owner: sreview
    group: sreview
    mode: 0644
  with_items:
  - { file: "{{ sreview.preroll }}", name: "preroll" }
  - { file: "{{ sreview.postroll }}", name: "postroll" }
