---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
  - git
  - ffmpeg
  - libmojolicious-perl
  - libdbd-pg-perl
  - libglib-perl
  - gir1.2-gstreamer-1.0
  - libglib-object-introspection-perl
  - gir1.2-gst-plugins-base-1.0
  - gstreamer1.0-plugins-base
  - bs1770gain

- name: clone git repository
  become: true
  become_user: videoteam
  git:
    repo: https://github.com/yoe/sreview
    dest: /home/videoteam/sreview 

- name: write config file
  template:
    dest: /home/videoteam/sreview/scripts/config.pl
    owner: videoteam
    group: videoteam
    mode: 0600
    src: config.pl.j2
    force: no
