---
- name: install opsis related packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - cu
    - hdmi2usb-mode-switch
    - hdmi2usb-udev
    - voctomix-outcasts

- name: push the script to connect to the opsis
  copy:
    src: files/opsis
    dest: /usr/local/bin/opsis
    mode: 0755

- name: push ingest systemd unit file
  copy:
    src: "files/{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dest }}"
  with_items:
    - { src: 'videoteam-ingest.service', dest: 'videoteam-ingest.service' }
    - { src: 'videoteam-ingest.path',    dest: 'videoteam-ingest.path' }
  notify: systemd videoteam-ingest
