---
- name: install opsis related packages
  apt:
    name: "{{ item }}"
  with_items:
  - hdmi2usb-mode-switch
  - hdmi2usb-udev
  - voctomix-outcasts

- name: install serial terminal
  apt:
    name: "{{ serial_terminal }}"

- name: push the script to connect to the opsis
  template:
    src: templates/opsis.j2
    dest: /usr/local/bin/opsis
    mode: 0755

- name: push videoteam-ingest script
  template:
    src: templates/videoteam-ingest.j2
    dest: /usr/local/bin/videoteam-ingest
    mode: 0755

- name: push systemd videoteam-ingest.service
  copy:
    src: files/videoteam-ingest.service
    dest: /etc/systemd/system/videoteam-ingest.service
  notify: systemd videoteam-ingest

- name: push systemd videoteam-ingest.path
  copy:
    src: files/videoteam-ingest.path
    dest: /etc/systemd/system/videoteam-ingest.path
  notify: systemd videoteam-ingest
