---
- name: install opsis related packages
  apt:
    name: "{{ item }}"
  with_items:
  - hdmi2usb-mode-switch
  - hdmi2usb-udev
  - voctomix-outcasts

- name: install serial terminal
  apt:
    name: "{{ item }}"
  with_items: "{{ serial_terminal }}"

- name: push the script to connect to the opsis
  template:
    src: templates/opsis.j2
    dest: /usr/local/bin/opsis
    mode: 0755

- name: push videoteam-ingest script
  template:
    src: templates/videoteam-ingest.j2
    dest: /usr/local/bin/videoteam-ingest
    mode: 0755

- name: push systemd videoteam-ingest.service
  copy:
    src: files/videoteam-ingest.service
    dest: /etc/systemd/system/videoteam-ingest.service
  notify:
  - systemctl daemon-reload
  - systemctl enable videoteam-ingest

- name: push systemd videoteam-ingest.path
  copy:
    src: files/videoteam-ingest.path
    dest: /etc/systemd/system/videoteam-ingest.path
  notify:
  - systemctl daemon-reload
  - systemctl enable videoteam-ingest

- name: configure minicom for hdmi2usb
  copy:
    src: files/minirc.dfl
    dest: /home/{{ user_name }}/.minirc.dfl
  when: "'minicom' in serial_terminal"

- name: push systemd hdmi2usbd.service
  copy:
    src: files/hdmi2usbd.service
    dest: /etc/systemd/system/hdmi2usbd.service
  notify:
  - systemctl daemon-reload
  - systemctl enable hdmi2usbd
  when: "'hdmi2usbd' in serial_terminal"

- name: push systemd hdmi2usbd.path
  copy:
    src: files/hdmi2usbd.path
    dest: /etc/systemd/system/hdmi2usbd.path
  notify:
  - systemctl daemon-reload
  - systemctl enable hdmi2usbd
  when: "'hdmi2usbd' in serial_terminal"

- include: hdmi2usbmond.yml
  when: "'hdmi2usbd' in serial_terminal"
