---
- name: install opsis related packages
  apt:
    name: "{{ item }}"
  with_items:
  - cu
  - hdmi2usb-mode-switch
  - hdmi2usb-udev
  - voctomix-outcasts

- name: push the script to connect to the opsis
  copy:
    src: files/opsis
    dest: /usr/local/bin/opsis
    mode: 0755

- name: push systemd video-ingest.service
  template:
    src: templates/videoteam-ingest.service.j2
    dest: /etc/systemd/system/videoteam-ingest.service
  notify: systemd videoteam-ingest

- name: push systemd video-ingest.path
  copy:
    src: files/videoteam-ingest.path
    dest: /etc/systemd/system/videoteam-ingest.path
  notify: systemd videoteam-ingest
