---
- name: restart networking
  command: "/bin/systemctl restart networking.service"

- name: restart dnsmasq
  command: "/bin/systemctl restart dnsmasq.service"

- name: restart network-manager
  command: "/bin/systemctl restart NetworkManager.service"
