---
- name: restart networking
  command: "/bin/systemctl restart networking.service"
  become: true

- name: restart dnsmasq
  command: "/bin/systemctl restart dnsmasq.service"
  become: true

- name: restart network-manager
  command: "/bin/systemctl restart NetworkManager.service"
  become: true

- name: reboot
  when: ansible_connection != 'local'
  command: shutdown -r now "Reboot triggered by Ansible"
  become: true
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for reboot
  when: ansible_connection != 'local'
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port: "{{ ansible_port | default(22) }}"
    delay: 1
    timeout: 300
  become: false
