image: williamyeh/ansible:debian9

test:lint:
  script:
  - apt-get update && apt-get -y install python-pip
  - pip install ansible-lint
  - ansible-lint site.yml

test:role:apt:
  script:
  - echo "deb cdrom:[foobar test]/ stretch main" >> /etc/apt/sources.list
  - touch /etc/apt/apt.conf.d/30apt-proxy
  - ansible-playbook tests/apt.yml
  - apt-get update && apt-get -y install rolldice

test:role:bash:
  script:
  - ansible-playbook tests/bash.yml
  - bash -c "compgen -c unam |grep -q uname && exit || exit 1"

test:role:motd:
  script:
  - >
    ansible-playbook tests/motd.yml --extra-vars "conference_name='Seo Oden Prize Award'
    conference_town='Ieu Eun' conference_country=A-Io"
  - sh tests/motd/unit_test.sh

test:role:opsis:
  script:
  - ansible-playbook tests/opsis.yml --skip-tags="no_unit_test"

test:role:system-software:
  script:
  - ansible-playbook tests/system-software.yml --skip-tags="no_unit_test"

test:role:users:
  script:
  - apt-get update && apt-get -y install locales
  - >
    ansible-playbook tests/users.yml --skip-tags="no_unit_test"
    --extra-vars "user_password_crypted=$6$xTGL7UF9T$XKcP/7PwBnKP2xC16T7gFOAhYr3zbIDL2Zu0.G6G88ljBYNHC3xtsKxFXv8RcGLHBI50i2gZChLXEdmU1e6aM1"

build:pages:
  image: alpine
  script:
  - apk --no-cache add py-sphinx python3 make
  - cd docs
  - make html
  - mv _build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
