image: williamyeh/ansible:debian9

lint:
  script:
  - apt-get update && apt-get -y install python-pip
  - pip install ansible-lint
  - ansible-lint site.yml

apt:
  script:
  - echo "deb cdrom:[foobar test]/ stretch main" >> /etc/apt/sources.list
  - touch /etc/apt/apt.conf.d/30apt-proxy
  - ansible-playbook tests/apt.yml
  - apt-get update && apt-get -y install rolldice
