image: williamyeh/ansible:debian9

lint:
  script:
  - apt-get update && apt-get -y install python-pip
  - pip install ansible-lint
  - ansible-lint site.yml

apt:
  script:
  - echo "deb cdrom:[foobar test]/ stretch main" >> /etc/apt/sources.list
  - touch /etc/apt/apt.conf.d/30apt-proxy
  - ansible-playbook tests/apt.yml
  - apt-get update && apt-get -y install rolldice

bash:
  script:
  - ansible-playbook tests/bash.yml
  - bash -c "compgen -c unam |grep -q uname && exit || exit 1"

motd:
  script:
  - >
    ansible-playbook tests/motd.yml --extra-vars "conference_name='Seo Oden Prize Award'
    conference_town='Ieu Eun' conference_country=A-Io"
  - sh tests/motd/unit_test.sh

opsis:
  script:
  - ansible-playbook tests/opsis.yml --skip-tags="no_unit_test"
