---
- hosts: all
  roles:
  - system-software
  - users

- hosts: dhcp-server
  roles:
  - dhcp-server
  - tftp-server
  - squid-deb-proxy

- hosts: icecast2
  roles:
  - icecast2

- hosts: onsite
  roles:
  - apt
  - bash
  - motd
  - staticips

- hosts: opsis
  roles:
  - opsis
  - xorg

- hosts: voctomix
  roles:
  - voctomix
  - blackmagic
  - xorg

- hosts: veyepar-encoder
  roles:
  - veyepar-encoder
