---
- hosts: all
  roles:
    - system-software
    - users

- hosts: onsite
  roles:
    - apt
    - bash
    - motd

- hosts: voctomix
  roles:
    - nodm
    - voctomix

- hosts: opsis
  roles:
    - opsis

- hosts: icecast2
  roles:
    - icecast2
