---
- hosts: all
  roles:
    - system-software
    - users

- hosts: dhcp-server
  roles:
    - dhcp-server
    - tftp-server

- hosts: icecast2
  roles:
    - icecast2

- hosts: onsite
  roles:
    - apt
    - bash
    - motd

- hosts: opsis
  roles:
    - opsis
    - nodm
    - xorg

- hosts: voctomix
  roles:
    - nodm
    - voctomix
    - xorg
