---
- name: install useful common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ack-grep
    - curl
    - emacs-nox
    - gdb
    - htop
    - iftop
    - iotop
    - ipython
    - lshw
    - moreutils
    - screen
    - strace
    - tcpdump
    - tmux
    - tree
    - vim-nox
    - vnstat
