---
- name: install useful common packages
  apt:
    name: "{{ item }}"
  with_items:
  - ack-grep
  - alsa-utils
  - autossh
  - curl
  - emacs-nox
  - etckeeper
  - ethtool
  - gdb
  - git
  - htop
  - iftop
  - iotop
  - ipython
  - less
  - lldpd
  - lshw
  - moreutils
  - mtr-tiny
  - net-tools
  - psmisc
  - python3-software-properties
  - rsync
  - screen
  - strace
  - tcpdump
  - time
  - tmux
  - tree
  - vim-nox
  - vnstat

- name: install firmware packages
  apt:
    name: "{{ item }}"
  with_items: "{{ firmware_packages }}"
