---
- name: install parts of veyepar for encoding
  apt:
    name: "{{ item }}"
  with_items:
  - build-essential
  - gir1.2-gst-plugins-base-1.0
  - gir1.2-gstreamer-1.0
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-ugly
  - gstreamer1.0-tools
  - imagemagick
  - inkscape
  - libpq-dev
  - libpq5
  - melt
  - python3-dev
  - python3-gi
  - python3-venv
  - tmux

- name: veyepar ve py pip requirements
  pip:
    requirements: "/home/{{ user_name }}/veyepar/setup/nodes/encode/requirements.txt"
    virtualenv: "/home/{{ user_name }}/.virtualenvs/veyepar"
    virtualenv_command: pyvenv
    virtualenv_site_packages: true
  become: true
  become_user:  "{{ user_name }}"
