---
- name: Install konversation
  apt:
    name: "{{ item }}"
  with_items:
  - konversation

- name: Create konversation main config
  template:
    src: templates/konversationrc.j2
    dest: "/home/{{ user_name }}/.config/konversationrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Autostart konversation
  copy:
    src: files/org.kde.konversation.desktop
    dest: /etc/xdg/autostart/org.kde.konversation.desktop
    owner: root
    group: root
  when: irc.autostart

- name: Diasable konversation autostart
  file:
    path: /etc/xdg/autostart/org.kde.konversation.desktop
    state: absent
  when: not irc.autostart
