---
- name: Install konversation
  apt:
    name: "{{ item }}"
  with_items:
  - konversation

- name: Create konversation main config
  template:
    src: templates/konversationrc.j2
    dest: "/home/{{ user_name }}/.config/konversationrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: install konversation systemd unit
  copy:
    src: files/videoteam-konversation.service
    dest: /etc/systemd/user/videoteam-konversation.service
  notify: reload-systemd

- name: enable konversation systemd unit
  file:
    state: link
    src: /etc/systemd/user/videoteam-konversation.service
    dest: "/home/{{ user_name }}/.config/systemd/user/xlogin.target.wants/videoteam-konversation.service"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
