---
- name: install lightdm
  apt:
    pkg: "{{ item }}"
  with_items:
  - lightdm-gtk-greeter
  - lightdm
  - policykit-1
  - x11-xserver-utils

- name: create dir for configs
  file:
    path: /etc/lightdm/lightdm.conf.d
    state: directory

- name: configure lightdm autologin
  template:
    src: templates/autologin.conf.j2
    dest: /etc/lightdm/lightdm.conf.d/autologin.conf
  when: autologin
  notify: restart lightdm

- name: Create xlogin|out.target
  copy:
    src: files/{{ item }}.target
    dest: /etc/systemd/user/{{ item }}.target
  notify: reload-systemd
  with_items:
  - xlogin
  - xlogout

- name: Drive xlogin|out.target
  template:
    src: debconfvideo-session-wrapper.j2
    dest: /usr/local/bin/debconfvideo-session-wrapper
    mode: 0755

- name: Hook our session wrapper into lightdm
  copy:
    src: files/xlogin.conf
    dest: /etc/lightdm/lightdm.conf.d/xlogin.conf
  notify: restart lightdm
