---
- name: configure lightdm autologin
  template:
    src: templates/autologin.conf.j2
    dest: /etc/lightdm/lightdm.conf.d/autologin.conf
  when: autologin

- name: install lightdm
  apt:
    pkg: "{{ item }}"
  with_items:
  - lightdm-gtk-greeter
  - lightdm
  - policykit-1
  - x11-xserver-utils

- name: kill pulseaudio with fire on logout
  file:
    src: templates/kill-pulseaudio.conf
    dest: /etc/lightdm/lightdm.conf.d/kill-pulseaudio.conf
