---
- name: install X
  apt:
    name: xserver-xorg

- name: install desktop tools
  apt:
    name: "{{ item }}"
  with_items:
  - hexchat
  - vim-gtk3
  - xul-ext-ublock-origin

- include: xfce4.yml
- include: xscreensaver.yml
