---
- name: install X
  apt:
    name: xserver-xorg

- name: install desktop tools
  apt:
    name: "{{ item }}"
  with_items:
  - vim-gtk3
  - mesa-utils
  - xul-ext-ublock-origin

- name: install useful video packages
  apt:
    name: "{{ item }}"
  with_items:
  - ffmpeg
  - gstreamer1.0-plugins-bad
  - gstreamer1.0-plugins-base
  - gstreamer1.0-plugins-good
  - gstreamer1.0-plugins-ugly
  - gstreamer1.0-tools
  - gstreamer1.0-x
  - mplayer
  - totem
  - vlc
  - mediainfo
  - v4l-utils
