---
- name: Script to start/stop all the services
  template:
    src: templates/control-all-the-things.j2
    dest: /usr/local/bin/{{ item }}-all-the-things
    mode: 0755
  with_items:
  - stop
  - start

- name: Script to show streams
  template:
    src: templates/videoteam-show-streams.j2
    dest: /usr/local/bin/videoteam-show-streams
    mode: 0755
  when: streaming.method == 'rtmp' and streaming.frontend is defined
