- name: install a desktop manager (xfce)
  apt:
    name: "{{ item }}"
  with_items:
  - pavucontrol
  - pulseaudio
  - xfce4
  - xfce4-pulseaudio-plugin
  - xfce4-notifyd
  - xfce4-terminal

- name: copy xfce4 configuration script
  copy:
    src: files/xfce4-debconfvideo-config
    dest: /usr/local/bin/xfce4-debconfvideo-config
    mode: 0755
  notify: run xfce4 configuration script
