- name: install a desktop manager (xfce)
  apt:
    name: "{{ item }}"
  with_items:
  - gvfs
  - nautilus
  - pavucontrol
  - pulseaudio
  - thunar-volman
  - xfce4
  - xfce4-notifyd
  - xfce4-pulseaudio-plugin
  - xfce4-terminal

- name: install an XFCE icon pack (Ubuntu)
  apt:
    name: xubuntu-icon-theme
  when: ansible_distribution == 'Ubuntu'

- name: copy xfce4 configuration script
  copy:
    src: files/xfce4-debconfvideo-config
    dest: /usr/local/bin/xfce4-debconfvideo-config
    mode: 0755
  notify: run xfce4 configuration script
