---
- name: push the debian apt sources.list
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
  notify: apt update
  when: ansible_distribution == 'Debian' and update_apt_sources

- name: set debian apt preferences
  template:
    src: templates/default-release.j2
    dest: /etc/apt/preferences.d/10-default-release
  when: ansible_distribution == 'Debian' and update_apt_sources

- name: add timvideos ppas
  apt_repository:
    repo: "ppa:timvideos/{{ item }}"
  with_items:
  - fpga-support
  - hdmi2usb
  - voctomix
  when: ansible_distribution == 'Ubuntu'

- name: set apt configuration
  copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  with_fileglob:
  - files/apt.conf.d/*

# d-i puts the apt config in apt.conf, but we prefer a .d file
- name: ensure apt proxy isn't in apt.conf
  lineinfile:
    dest: /etc/apt/apt.conf
    regexp: ^Acquire::http::Proxy
    state: absent

- name: setup apt proxy
  template:
    src: templates/30apt-proxy.j2
    dest: /etc/apt/apt.conf.d/30apt-proxy
  when: apt_proxy != ""

- name: unconfigure apt proxy
  file:
    path: /etc/apt/apt.conf.d/30apt-proxy
    state: absent
  when: apt_proxy == ""
