---
- name: push the sources.list
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  notify: apt update

- name: set apt preferences
  copy:
    src: "{{ item }}"
    dest: /etc/apt/preferences.d/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/preferences.d/*

- name: set apt configuration
  copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/apt.conf.d/*
