---
- name: push the debian apt sources.list
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
  notify: apt update
  when: ansible_distribution == 'Debian' and update_apt_sources

- name: add sid to sources.list.d
  template:
    src: templates/sid.list.j2
    dest: /etc/apt/sources.list.d/sid.list
  notify: apt update
  when: ansible_distribution == 'Debian' and enable_sid

- name: set apt preferences that prefer non-sid
  template:
    src: templates/default-release.j2
    dest: /etc/apt/preferences.d/10-default-release
  when: ansible_distribution == 'Debian' and enable_sid

- name: add timvideos ppas
  apt_repository:
    repo: "ppa:timvideos/{{ item }}"
  with_items:
  - fpga-support
  - voctomix
  when: ansible_distribution == 'Ubuntu'

- name: set apt configuration
  copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  with_fileglob:
  - files/apt.conf.d/*

- name: unconfigure apt proxy that D-I set
  file:
    path: /etc/apt/apt.conf.d/30apt-proxy
    state: absent
  when: not apt_proxy
