---
- name: push the sources.list
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
  notify: apt update

- name: set apt preferences
  template:
    src: templates/default-release.j2
    dest: /etc/apt/preferences.d/10-default-release

- name: set apt configuration
  copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  with_fileglob:
    - files/apt.conf.d/*
