---
time_zone: UTC
domain: video.debconf.org

apt_proxy: false

user_name: videoteam
# Defaults to not setting a password
#user_password_crypted: changeme

playbook_repo: https://salsa.debian.org/debconf-video-team/ansible
playbook_branch: master

# To replace the stock inventory with your own, point at your own github repo
inventory_repo: ''
inventory_branch: master

vault_pw: ''

# boot image sources
debian_host: deb.debian.org
ubuntu_host: archive.ubuntu.com

debian_suites: [stretch]
ubuntu_suites: []
archs: [amd64]

# Wait forever
pxe_timeout: -1
