---
time_zone: UTC
domain: video.debconf.org

apt_proxy: false
# Defaults to deb.debian.org | archive.ubuntu.com
#mirror: deb.debian.org
debian_version: stretch

user_name: videoteam
# Defaults to not setting a password
#user_password_crypted: changeme

# Git repos:
playbook_repo: https://anonscm.debian.org/cgit/debconf-video/ansible.git
playbook_branch: master

# To replace the stock inventory with your own,
#   point at your own github repo
#inventory_repo: https://gitlab.com/yourname/ansible-inventory
#inventory_branch: master


# boot image sources
debian_host: ftp.debian.org
ubuntu_host: archive.ubuntu.com

debian_suites: [stretch, sid]
ubuntu_suites: [xenial, zesty, artful]
archs: [amd64]

others:

    - label: memtest86+
      url: http://www.memtest.org/download/5.01/
      filename: memtest86+-5.01.bin.gz
      loader: linux16

    - label: tomsrtbt
      url: http://www.ibiblio.org/pub/Linux/system/recovery/
      filename: tomsrtbt-2.0.103.tar.gz
      loader: linux16 memdisk

