---
irc_room_channel: "#debconf17-bo"
irc_nick: videoteam_bo
room_name: bo

blackmagic_sources:
- card: 0
  connection: SDI
  audio: true
  # check the frequency setting on the camera
  # make sure it matches what's the frequency of the local power
  # use BlackmagicDesktopVideoSetup to see what the camera is sending
  # 720p59.94 is 18
  # 720p50 is 17
  # list of all mode IDs: check 'gst-inspect-1.0 decklinkvideosrc'
  mode: "{{ blackmagic_default_mode }}"
- card: 1
  connection: SDI
  audio: true
  mode: "{{ blackmagic_default_mode }}"

voctolights:
- camera: Cam2
  port: /dev/ttyUSB0
