---
irc_room_channel: "#debconf17-rex"
irc_nick: videoteam_rex
room_name: rex

blackmagic_sources:
- card: 0
  connection: SDI
  audio: true
  # 720p59.94
  # list of mode IDs: check 'gst-inspect-1.0 decklinkvideosrc'
  mode: 18
- card: 1
  connection: SDI
  audio: true
  mode: 18

audiosource: Cam2
