---
- name: create letsencrypt account key
  openssl_privatekey:
    state: present
    path: "{{ letsencrypt_account_key }}"

- name: request letsencrypt signing
  letsencrypt:
    csr: "{{ csr_path }}"
    dest: "{{ certificate_path }}"
    challenge: http-01
    account_key: "{{ letsencrypt_account_key }}"
    account_email: "{{ letsencrypt_account_email }}"
    acme_directory: "{{ letsencrypt_acme_directory }}"
    agreement: "{{ letsencrypt_agreement }}"
  register: letsencrypt_challenge

- name: answer letsencrypt challenge
  include_tasks: letsencrypt_challenge.yml
  when: letsencrypt_challenge|changed

- name: download certificate chain
  get_url:
    url: "{{ letsencrypt_acme_directory|replace('/directory', '/acme') }}/issuer-cert"
    dest: "{{ letsencrypt_chain_path }}.der"
  register: download_chain

- name: convert certificate chain
  command: openssl x509 -inform der -in {{ letsencrypt_chain_path }}.der -outform pem -out {{ letsencrypt_chain_path }}
  when: download_chain|changed

- name: generate full chain
  shell: /bin/cat {{ certificate_path|quote }} {{ letsencrypt_chain_path }} > {{ fullchain_path|quote }}
  when: letsencrypt_challenge|changed and letsencrypt_response|changed or download_chain|changed
