---
- name: create nginx configuration for well-known directory
  copy:
    dest: "{{ nginx_snippet_path }}"
    content: |
      location /.well-known/ {
        alias {{ letsencrypt_well_known_dir }}/;
      }
    owner: root
    group: root
    mode: 0644
  tags:
    - tls-certificates

- name: add temporary nginx vhost for well-known data
  copy:
    dest: /etc/nginx/sites-enabled/tmp-letsencrypt-{{ basename }}.conf
    content: |
      server {
        listen 80;
        listen [::]:80;

        server_name {{ common_name }} {{ subject_alt_names|join(' ') }};

        include {{ nginx_snippet_path }};
      }
    owner: root
    group: root
    mode: 0644
  when: letsencrypt_do_nginx_vhost
  tags:
    - tls-certificates

- name: reload nginx after well-known stuff
  command: systemctl reload nginx
  tags:
    - tls-certificates
