---
- name: install required dependencies
  apt:
    pkg: "{{ item }}"
  with_items:
    - openssl
    - python-openssl

- name: create directories for tls certificates
  include_tasks: create_directories.yml

- name: create private key and csr
  include_tasks: create_keypair.yml

- name: sign certificate with letsencrypt
  include_tasks: letsencrypt.yml
  when: not self_sign

- name: self-sign certificate
  include_tasks: self_sign.yml
  when: self_sign
