---
# We can't just use a .d file because d-i will have written a DHCP entry into interfaces
- name: Write static /etc/network/interfaces
  template:
    src: templates/interfaces.j2
    dest: /etc/network/interfaces
  when: staticips.write_interfaces
  notify:
  - kill lingering dhclients
  - restart networking
  tags:
  - staticips
