---
# We've rewritten interfaces to not be dhcp any more, so ifdown won't stop the dhclient
- name: kill lingering dhclients
  command: killall dhclient
  ignore_errors: yes
- name: restart networking
  command: systemctl restart networking
