---
- name: create d-i directory
  file:
    path: /srv/pxe/d-i/
    state: directory

- name: copy d-i supporting files
  copy:
    src: files/scripts
    dest: /srv/pxe/

- name: copy static preseeds
  copy:
    src: files/d-i/{{ item }}
    dest: /srv/pxe/d-i/
  with_items: "{{ debian_suites + ubuntu_suites }}"

- name: write preseed_local_flavor.cfg
  template:
    src: preseed_local.cfg.j2
    dest: /srv/pxe/d-i/preseed_local_{{item.key}}.cfg
  with_dict:
    debian: "{{ debian_host }}"
    ubuntu: "{{ ubuntu_host }}"
