---
- name: create d-i directory
  file:
    path: /srv/pxe/
    state: directory

- name: copy preseed and supporting files
  copy:
    src: files/{{ item }}
    dest: /srv/pxe/
  with_items:
  - d-i
  - ec

