---
- name: download TFTP boot image
  get_url:
    url: "{{ netboot_image }}"
    dest: /srv/tftp/netboot.tar.gz

- name: extract TFTP boot image
  unarchive:
    src: /srv/tftp/netboot.tar.gz
    dest: /srv/tftp
    remote_src: true
    creates: /srv/tftp/pxelinux.0

- name: inject preseed into menu (find files)
  find:
    paths: /srv/tftp
    recurse: true
    patterns: txt.cfg
  register: menus

- name: inject preseed into menu (do injection)
  lineinfile:
    dest: "{{ item.path }}"
    regexp: (\s+append vga=.*\s+initrd=\S+)\s+(?!auto=true)(.*)
    backrefs: true
    line: \1 auto=true interface=auto url={{ inventory_hostname }} DEBCONF_DEBUG=5 partman-auto/disk="/dev/sda" \2
  with_items: "{{ menus.files }}"

- name: create d-i directory
  file:
    path: /srv/pxe/d-i/{{ item }}
    state: directory
    recurse: true
  with_items:
  - stretch
  - xenial

- name: write preseed.cfg
  template:
    src: preseed.cfg.j2
    dest: /srv/pxe/d-i/{{ item }}/preseed.cfg
  with_items:
  - stretch
  - xenial

- name: generate late_command.sh
  template:
    src: late_command.sh.j2
    dest: /srv/pxe/d-i/late_command.sh
