---
- name: create d-i directory
  file:
    path: /srv/pxe/
    state: directory

- name: copy preseed and supporting files
  copy:
    src: files/{{ item }}
    dest: /srv/pxe/
  with_items:
  - d-i
  - ec

- name: write preseed_local_flavor.cfg
  template:
    src: preseed_local.cfg.j2
    dest: /srv/pxe/d-i/preseed_local_{{item.key}}.cfg
  with_dict:
    debian: "{{ debian_host }}"
    ubuntu: "{{ ubuntu_host }}"
