---
- name: download TFTP boot image
  get_url:
    url: "{{ netboot_image }}"
    dest: /srv/tftp/netboot.tar.gz

- name: extract TFTP boot image
  unarchive:
    src: /srv/tftp/netboot.tar.gz
    dest: /srv/tftp
    remote_src: true
    creates: /srv/tftp/pxelinux.0

- name: write preseed.cfg
  template:
    src: preseed.cfg.j2
    dest: /srv/tftp/preseed.cfg

- name: inject preseed into menu (find files)
  find:
    paths: /srv/tftp
    recurse: true
    patterns: txt.cfg
  register: menus

- name: inject preseed into menu (do injection)
  lineinfile:
    dest: "{{ item.path }}"
    regexp: (\s+append\s+.*\s+initrd=\S+)\s+(?!auto=true)(.*)
    backrefs: true
    line: \1 auto=true interface=auto url=tftp://10.20.0.1/preseed.cfg \2
  with_items: "{{ menus.files }}"
