---
- name: create boot image directories
  file:
    path: /srv/tftp/{{item}}
    state: directory
    recurse: true
    mode: 0750
  with_items:
    - grub
    - ubuntu
    - util/cz/exper/live

- name: write grub.cfg
  template:
    src: grub.cfg.j2
    dest: /srv/tftp/grub/grub.cfg

- name: create debian suite dirs
  file:
    path: /srv/tftp/debian/{{ item[0] }}/{{ item[1] }}
    state: directory
    recurse: true
    mode: 0750
  with_nested:
    - "{{ debian_suites }}"
    - "{{ archs }}"


- name: create utunbu suite dirs
  file:
      # path: /srv/tftp/ubuntu/{{suite}}/{{arch}}
    path: /srv/tftp/ubuntu/{{ item[0] }}/{{ item[1] }}
    state: directory
    recurse: true
    mode: 0750
  with_nested:
    - "{{ ubuntu_suites }}"
    - "{{ archs }}"

- name: download debian netboot images
  get_url:
    url: http://ftp.debian.org/debian/dists/{{item[0]}}/main/installer-{{item[1]}}/current/images/netboot/debian-installer/{{item[1]}}/{{item[2]}}
    dest: /srv/tftp/debian/{{ item[0] }}/{{ item[1] }}/{{ item[2] }}
  with_nested:
    - "{{ debian_suites }}"
    - "{{ archs }}"
    - [ 'linux', 'initrd.gz' ]

- name: download ubuntu netboot images
  get_url:
    url: http://{{ubuntu_host}}/ubuntu/dists/{{item[0]}}/main/installer-{{item[1]}}/current/images/netboot/ubuntu-installer/{{item[1]}}/{{item[2]}}
    dest: /srv/tftp/ubuntu/{{ item[0] }}/{{ item[1] }}/{{ item[2] }}
  with_nested:
    - "{{ ubuntu_suites }}"
    - "{{ archs }}"
    - [ 'linux', 'initrd.gz' ]

- name: download ubuntu updated netboot images
  get_url:
    url: http://{{ubuntu_host}}/ubuntu/dists/{{item[0]}}-updates/main/installer-{{item[1]}}/current/images/netboot/ubuntu-installer/{{item[1]}}/{{item[2]}}
    dest: /srv/tftp/ubuntu/{{ item[0] }}/{{ item[1] }}/{{ item[2] }}
  ignore_errors: true
  with_nested:
    - "{{ ubuntu_suites }}"
    - "{{ archs }}"
    - [ 'linux', 'initrd.gz' ]

