---
- name: install icecast
  apt:
    name: icecast2

- name: push icecast default file
  copy:
    src: files/icecast2
    dest: /etc/default/icecast2

- name: push icecast configuration file
  template:
    src: templates/icecast.xml.j2
    dest: /etc/icecast2/icecast.xml
