---
- name: enable videoteam-ingest.path
  service:
    name: videoteam-ingest.path
    enabled: yes

- name: enable hdmi2usbd
  service:
    name: hdmi2usbd
    enabled: yes

- name: enable hdmi2usbmond
  service:
    name: hdmi2usbmond
    enabled: yes
