---
- name: install nginx packages
  apt:
    pkg: "{{ item }}"
    state: latest
    default_release: "{{ debian_version }}-backports"
  with_items:
    - nginx-extras
    - libnginx-mod-rtmp
    - libnginx-mod-http-fancyindex
  notify: restart nginx
  tags:
    - streaming

- name: install ffmpeg
  apt:
    pkg: ffmpeg
  tags:
    - streaming

- name: create nginx content directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  with_items:
  - "{{ streaming.backend.data_root }}"
  - "{{ streaming.backend.data_root }}/www"
  - "{{ streaming.backend.data_root }}/hls"
  - "{{ streaming.backend.data_root }}/dump"
  tags:
    - streaming

- name: use tmpfs for hls
  lineinfile:
    dest: /etc/fstab
    line: "tmpfs {{ streaming.backend.data_root }}/hls tmpfs uid=www-data,gid=www-data,mode=0755 0 2"
    regexp: "\\s{{ streaming.backend.data_root }}/hls\\s"
  notify: mount all

  with_items:
  - "{{ streaming.backend.data_root }}"
  - "{{ streaming.backend.data_root }}/www"
  - "{{ streaming.backend.data_root }}/hls"
  - "{{ streaming.backend.data_root }}/dump"
  tags:
    - streaming

- name: create nginx dump directories for rooms
  file:
    path: "{{ streaming.backend.data_root }}/dump/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  with_items: "{{ streaming.rooms }}"
  when: streaming.dump
  tags:
    - streaming

- name: create nginx rtmp socket directory
  file:
    path: /var/lib/nginx/rtmp
    state: directory
    owner: www-data
    group: root
    mode: 0700
  tags:
    - streaming

- name: remove default html directory
  file:
    path: /var/www/html
    state: absent
  tags:
    - streaming

- name: disable nginx default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
  tags:
    - streaming

- name: install nginx streaming backend site configuration
  template:
    src: nginx/sites-enabled/streaming-backend.conf.j2
    dest: /etc/nginx/sites-enabled/streaming-backend.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  tags:
    - streaming

- name: install nginx streaming backend rtmp configuration
  template:
    src: nginx/nginx-rtmp.conf.j2
    dest: /etc/nginx/nginx-rtmp.conf
  notify: reload nginx
  tags:
    - streaming
    - streaming-backend_config

- name: patch nginx.conf to include the rtmp configuration
  lineinfile:
    dest: /etc/nginx/nginx.conf
    line: "include /etc/nginx/nginx-rtmp.conf;"
    state: present
  notify: reload nginx
  tags:
    - streaming
    - streaming-backend_config

- name: patch nginx.conf to use 1 worker
  # https://github.com/arut/nginx-rtmp-module/issues/849
  lineinfile:
    dest: /etc/nginx/nginx.conf
    line: "worker_processes 1;"
    regexp: "^worker_processes"
    state: present
  notify: reload nginx
  tags:
    - streaming
    - streaming-backend_config

- name: create index.html for streaming backend
  template:
    src: index.html.j2
    dest: "{{ streaming.backend.data_root }}/www/index.html"
    owner: www-data
    group: www-data
    mode: 0644
  tags:
    - streaming
