---
- name: install nginx packages
  apt:
    pkg: "{{ item }}"
    state: latest
    default_release: "{{ debian_version }}-backports"
  with_items:
    - nginx-extras
  notify: restart nginx
  tags:
    - streaming

- name: install geoip from contrib
  apt:
    pkg: "{{ item }}"
    state: latest
    default_release: "{{ debian_version }}-backports"
  with_items:
    - geoip-database-contrib
  tags:
    - streaming

- name: create nginx content directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  with_items:
  - "{{ streaming.frontend.data_root }}"
  - "{{ streaming.frontend.data_root }}/www"
  - "{{ streaming.frontend.data_root }}/hls"
  tags:
    - streaming

- name: remove default html directory
  file:
    path: /var/www/html
    state: absent
  tags:
    - streaming

- name: disable nginx default configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
  tags:
    - streaming

- name: check if nginx vhost exists
  stat:
    path: /etc/nginx/sites-enabled/streaming-frontend.conf
  register: nginx_vhost
  tags:
    - streaming

- name: generate tls certificate
  include_role:
    name: tls-certificates
  vars:
    basename: streaming_frontend
    common_name: "{{ inventory_hostname }}"
    subject_alt_names: "{{ streaming.frontend.server_names }}"
    self_sign: False
    letsencrypt_do_nginx_vhost: not nginx_vhost.stat.exists
  tags:
    - streaming

- name: install nginx streaming frontend site configuration
  template:
    src: nginx/sites-enabled/streaming-frontend.conf.j2
    dest: /etc/nginx/sites-enabled/streaming-frontend.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx
  tags:
    - streaming
    - streaming_frontend_config

- name: create index.html for streaming frontend
  template:
    src: index.html.j2
    dest: "{{ streaming.frontend.data_root }}/www/index.html"
    owner: www-data
    group: www-data
    mode: 0644
  tags:
    - streaming
