---

user_name: videoteam

# Dir that contains workin veyepar checkout with secrets in place
# like on a developer's laptop,
# best to pass this on the command line:
# --extra-vars="{'veyepar_confs': '/home/carl/src/veyepar'}"
# veyepar_confs: /home/carl/src/veyepar

# Entity that produces and uploads, like DebConf Video Team, or NDV.
# used for credits image and upload credentials
publisher: dcvt

org: debian
show: dcX

# URL of veyepar website
# used to get data from the db, like:
# https://veyepar.nextdayvideo.com/main/C/chicagolug/S/dec_2017/asset_names.json
veyepar_url: https://veyepar.nextdayvideo.com
