---
- name: install the necessary packages
  apt:
    name: "{{ item }}"
  with_items:
  - sreview-master
  - sreview-detect
  - postgresql-client

- name: ensure sreview-dispatch runs
  systemd:
    name: sreview-dispatch
    enabled: true
    state: started

- name: create pubdir
  file:
    name: /srv/{{nfs_server}}/sreview/web/public
    state: directory
    owner: sreview
    group: sreview
    mode: 0755
