---
- name: create our main user
  user:
    name: "{{ user_name }}"
    groups: audio,dialout,plugdev,sudo,video
    password: "{{ user_password_crypted }}"
  when: user_password_crypted is defined

- name: ensure ~/.ssh directory for our main user
  file:
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    path: "/home/{{ user_name }}/.ssh"

- name: install sudo
  apt:
    name: sudo

- name: manage onsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ item }}"
  with_items: "{{public_keys_onsite}}"
  when: "'onsite' in group_names"
  tags:
    - authorized_keys

- name: manage offsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ item }}"
  with_items: "{{public_keys_offsite}}"
  when: "'offsite' in group_names"
  tags:
    - authorized_keys

- name: manage ssh private_key
  copy:
    content: "{{ ssh_private_key }}"
    dest: "/home/{{ user_name }}/.ssh/id_ed25519"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0600
  when: ssh_private_key is defined
  tags:
    - authorized_keys

- name: manage root ssh authorized_keys
  authorized_key:
    user: root
    key: "{{ item }}"
  with_items: "{{public_keys_root}}"
  tags:
    - authorized_keys

- name: configure locale
  locale_gen:
    name: en_US.UTF-8
    state: present
  notify: update locale

- name: configure timezone
  timezone:
    name: "{{ time_zone }}"
  # fails in d-i
  ignore_errors: true

- name: ensure systemd wants directory exists
  file:
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    path: "/home/{{ user_name }}/.config/systemd/user/xlogin.target.wants"
    recurse: true
