---
- name: create our main user
  user:
    name: "{{ user_name }}"
    groups: audio,plugdev,sudo,video
    password: "{{ user_password |password_hash('sha512', pw_salt) }}"
    shell: /bin/bash

- name: install sudo
  apt:
    name: sudo

- name: manage onsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ item }}"
  with_items: "{{public_keys_onsite}}"
  when: "'onsite' in group_names"

- name: manage offsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ item }}"
  with_items: "{{public_keys_offsite}}"
  when: "'offsite' in group_names"

- name: manage root ssh authorized_keys
  authorized_key:
    user: root
    key: "{{ item }}"
  with_items: "{{public_keys_root}}"

- name: configure locale
  command: update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
  when: ansible_env.LANG != 'en_US.UTF-8'

- name: ensure systemd wants directory exists
  file:
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    path: "/home/{{ user_name }}/.config/systemd/user/default.target.wants"
    recurse: true
