- name: create our main user
  user:
    name: "{{ user_name }}"
    groups: sudo,video
    password: "{{ user_password |password_hash('sha512', pw_salt) }}"

- name: install sudo
  apt:
    name: sudo

- name: manage onsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "public_keys/onsite/*"
  when: "'onsite' in group_names"

- name: manage offsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "public_keys/offsite/*"
  when: "'offsite' in group_names"
