- name: create our main user
  user:
    name: "{{ user_name }}"
    group: "{{ user_group }}"
    groups: sudo
    password: "{{ user_password |password_hash('sha512') }}"

- name: manage onsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "public_keys/onsite/*"
  when: "'onsite' in group_names"

- name: manage offsite ssh authorized_keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "public_keys/offsite/*"
  when: "'offsite' in group_names"
