- name: run xfce4 configuration script
  command: /usr/local/bin/xfce4-debconfvideo-config
  become: true
  become_user: "{{ user_name }}"

- name: systemctl restart lightdm
  command: systemctl restart lightdm
