- name: run xfce4 configuration script
  command: /usr/local/bin/xfce4-debconfvideo-config
  become: true
  become_user: "{{ user_name }}"

- name: restart lightdm
  service:
    name: lightdm
    state: restarted

- name: reload-systemd
  command: systemctl daemon-reload
  tags:
  - skip_ansible_lint
