---
user_name: videoteam
storage_username: videodata

org: debian
show: debconf
room_name: change-me

sources:
- Cam1
- Cam2
- Grabber

voctomix:
  display_system: gl
  framerate: 25
  # loop_url: http://example.net/loop.tar.xz

streaming:
  method: none
  hq_config:
    video_bitrate: 2000 # kbps
    audio_bitrate: 128000 # bps
    keyframe_period: 60 # seconds
# rtmp:
#   threads: auto / vaapi
#   location: rtmp://a.rtmp.youtube.com/live2/x/SUPER_SECRET_KEY app=live2

blackmagic_sources: []
# Syntax:
# - card: 0
#   connection: SDI
#   audio: true
# Optional parameters:
#   mode: 18

rsync_excludes: []
rsync_sshopts: ""

#video_disk: /dev/sdb1
