---
user_name: videoteam
storage_username: videodata
debian_version: stretch

org: debian
show: debconf
room_name: change-me

sources:
- Cam1
- Cam2
- Grabber

# Local frequency setting, in Hz
# This can be either 50 or 60Hz
frequency: 50

voctomix:
  display_system: gl
  framerate: "{{ frequency / 2 }}"
  # loop_url: http://example.net/loop.tar.xz

streaming:
  method: none
  mix_channels: false
  hq_config:
    video_bitrate: 2000 # kbps
    audio_bitrate: 128000 # bps
    keyframe_period: 60 # seconds

#blackmagic_sources: []
# - card: 0
#   connection: SDI
#   audio: true
#   mode: 18  # optional
# - card: 1
#   connection: SDI
#   audio: false
#   mode: 17  # optional

rsync_excludes: []
rsync_sshopts: ""

# video_disk: /dev/sdb1

# voctolights:
# - camera: Cam1
#   port: /dev/ttyUSB0
#   host: localhost

# check the frequency setting on the camera
# make sure it matches what's the frequency of the local power
# use BlackmagicDesktopVideoSetup to see what the camera is sending
# list of all mode IDs: check 'gst-inspect-1.0 decklinkvideosrc'
frequency_parameters:
  50:
    mode: 17  # 720p50

  60:
    mode: 18  # 720p59.94

blackmagic_default_mode: "{{ frequency_parameters[frequency].mode }}"
