---
user_name: videoteam

org: debian
show: debconf
room_name: change-me

sources:
- Cam1
- Cam2
- Grabber

voctomix:
  display_system: gl
  framerate: 25

streaming: icecast

icecast_quality_hq: 18
icecast_quality_lq: 20

icecast_scale_hq: 720:-1
icecast_scale_lq: 480:-1

icecast_abr_hq: 96K
icecast_abr_lq: 64k

icecast_vbr_hq: 1.5M
icecast_vbr_lq: 200k

icecast_source: source:password@change.me:8000

# streaming: youtube
# youtube_auth: SUPER_SECRET_KEY
youtube_threads: auto

blackmagic_sources: []
# Syntax:
# - card: 0
#   connection: SDI
#   audio: true
# Optional parameters:
#   mode: 18

rsync_excludes: []

#video_disk: /dev/sdb1
