---
- name: install the dhcp server
  apt:
    name: dnsmasq
    state: present

- name: set udev rule to name the network interfaces
  template:
    src: templates/76-netnames.rules.j2
    dest: /etc/udev/rules.d/76-netnames.rules

- name: configure network interfaces (static)
  template:
    src: templates/interfaces-static.j2
    dest: /etc/network/interfaces
  when: use_static_ip
  notify: restart networking

- name: configure network interfaces (dhcp)
  template:
    src: templates/interfaces-dhcp.j2
    dest: /etc/network/interfaces
  when: not use_static_ip
  notify: restart networking

- name: create the TFTP root directory
  file:
    path: /srv/tftp
    state: directory

- name: configure the dhcp server
  template:
    src: templates/local.conf.j2
    dest: /etc/dnsmasq.d/local.conf
  notify: restart dnsmasq
