---
- name: install the dhcp server
  apt:
    name: dnsmasq

- name: set udev rule to name the network interfaces
  template:
    src: templates/76-netnames.rules.j2
    dest: /etc/udev/rules.d/76-netnames.rules
  notify:
  - reboot
  - wait for reboot
  tags:
  - staticips

- name: configure network interfaces (static)
  template:
    src: templates/interfaces-static.j2
    dest: /etc/network/interfaces
  when: use_static_ip
  notify: restart networking
  tags:
  - staticips

- name: configure network interfaces (dhcp)
  template:
    src: templates/interfaces-dhcp.j2
    dest: /etc/network/interfaces
  when: not use_static_ip
  notify: restart networking
  tags:
  - staticips

- name: ensure network-manager doesn't run its own dnsmasq
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: "^#?dns=dnsmasq$"
    line: "#dns=dnsmasq"
  notify: restart network-manager
  ignore_errors: yes

- name: create the TFTP root directory
  file:
    path: /srv/tftp
    state: directory

- name: configure the dhcp server
  template:
    src: templates/local.conf.j2
    dest: /etc/dnsmasq.d/local.conf
  notify: restart dnsmasq
  tags:
  - staticips

- name: configure the dhcp server for pxe
  template:
    src: templates/pxe.conf.j2
    dest: /etc/dnsmasq.d/pxe.conf
  notify: restart dnsmasq

- name: configure static hosts
  template:
    src: templates/machines.conf.j2
    dest: /etc/dnsmasq.d/machines.conf
  when: False and staticips is defined
  notify: restart dnsmasq
  tags:
  - staticips

- name: boxes
  template:
    src: templates/boxes.conf.j2
    dest: /etc/dnsmasq.d/boxes.conf
  when: boxes is defined
  notify: restart dnsmasq
