---
- name: install R&D related packages
  apt:
    name: "{{ item }}"
  with_items:
  - git
  - vim
  - vizzini-dkms
  - grub-ipxe

- name: install serial terminal
  apt:
    name: "{{ item }}"
  with_items:
      # - flterm
  - minicom

- name: configure minicom for hdmi2usb
  copy:
    src: files/minirc.dfl
    dest: /home/{{ user_name }}/.minirc.dfl

- name: git clone bunch of things
  git:
    repo: "https://github.com/{{ item[0] }}/{{ item[1] }}.git"
    dest: "/home/{{ user_name }}/{{ item[1] }}"
    depth: 1
    force: yes
  become: true
  become_user: "{{ user_name }}"
  with_list:
  - [timvideos, HDMI2USB-litex-firmware]
  - [CarlFK, clocky]
  - [CarlFK, voctomix-outcasts]
  - [ondrej1024, crelay] # turns usb relay's on and off

# scripts to dowload, install, build? firmware
- name: download-env-root
  shell: ./download-env-root.sh
  args:
    chdir: /home/{{ user_name }}/HDMI2USB-litex-firmware/scripts

- name: download-env
  shell: ./download-env.sh
  args:
    chdir: /home/{{ user_name }}/HDMI2USB-litex-firmware/scripts
    creates: /home/{{ user_name }}/HDMI2USB-litex-firmware/build
  become: true
  become_user: "{{ user_name }}"

- name: Create .Xilinx dir
  file:
    state: directory
    path: /home/{{ user_name }}/.Xilinx
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: copy Xilinx.lic
  copy:
    src: "{{ xilinx_lic }}"
    dest: /home/{{ user_name }}/.Xilinx/Xilinx.lic
  become: true
  become_user:  "{{ user_name }}"
  when: xilinx_lic is defined

- name: udev rule for relay board
  copy:
    src: files/51-sainsmart-usb.rules
    dest: /etc/udev/rules.d/51-sainsmart-usb.rules


