---
- name: install blackmagic capture systemd units
  template:
    src: templates/videoteam-capture-blackmagic.service.j2
    dest: /etc/systemd/user/videoteam-capture-blackmagic-{{ item.0 }}.service
  with_indexed_items: "{{ blackmagic_sources }}"
  notify: reload-systemd

- name: enable voctomix systemd units
  file:
    state: link
    src: /etc/systemd/user/videoteam-capture-blackmagic-{{ item.0 }}.service
    dest: /home/{{ user_name }}/.config/systemd/user/xlogin.target.wants/videoteam-capture-blackmagic-{{ item.0 }}.service
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_indexed_items: "{{ blackmagic_sources }}"
