---
- name: install useful video packages
  apt:
    name: "{{ item }}"
  with_items:
    - ffmpeg
    - mplayer
    - vlc

- include: voctomix.yml
- include: icecast.yml
  when: streaming == 'icecast'
