---
- include: video_disk.yml
  when: video_disk is defined
- include: voctomix.yml
- include: blackmagic.yml
- include: scripts.yml
- include: icecast.yml
  when: streaming.method == 'icecast'
- include: rtmp.yml
  when: streaming.method == 'rtmp'
