---
- include_tasks: video_disk.yml
  when: video_disk is defined

- include_tasks: voctomix.yml

- include_tasks: blackmagic.yml

- include_tasks: scripts.yml

- include_tasks: rtmp.yml
  when: streaming and streaming.method == 'rtmp'

- include_tasks: tallylight.yml
  when: voctolights is defined
  tags:
  - voctolight
