---
- name: install voctomix & related packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mplayer
    - vlc
    - voctomix
    - voctomix-outcasts

- name: create voctomix config dir
  file:
    path: /etc/voctomix
    state: directory

- name: configure voctomix
  copy:
    src: files/voctomix.ini
    dest: /etc/voctomix/voctomix.ini
    owner: root
    group: root
    mode: 644

- name: push the streaming scripts
  template:
    src: "templates/{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    owner: root
    group: root
    mode: 755
  with_items:
    - { src: 'stream-voctomix-hq.j2', dest: 'stream-voctomix-hq' }
    - { src: 'stream-voctomix-lq.j2', dest: 'stream-voctomix-lq' }

- name: push the monitoring script
  template:
    src: files/monitor-stdout
    dest: /usr/local/bin/monitor-stdout
    owner: root
    group: root
    mode: 755

- name: push the cutlist script
  template:
    src: files/wrap-generate-cutlist
    dest: /usr/local/bin/wrap-generate-cutlist
    owner: root
    group: root
    mode: 755

- name: install systemd unit files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/user/
    owner: root
    group: root
    mode: 644
  with_fileglob:
    - files/systemd/*
  #  notify:
