---

- name: Install VAAPI Packages
  apt:
    name: "{{ item }}"
  with_items:
  - gstreamer1.0-vaapi
  - i965-va-driver
  - intel-gpu-tools
  - vainfo
  when: streaming.rtmp.threads == 'vaapi'

- name: RTMP streaming script
  template:
    src: templates/videoteam-stream.j2
    dest: /usr/local/bin/videoteam-stream
    mode: 0755

- name: RTMP streaming systemd service
  copy:
    src: files/systemd/videoteam-stream.service
    dest: /etc/systemd/user/videoteam-stream.service
  notify: reload-systemd

- name: Enable RTMP streaming service
  file:
    state: link
    src: /etc/systemd/user/videoteam-stream.service
    dest: "/home/{{ user_name }}/.config/systemd/user/xlogin.target.wants/videoteam-stream.service"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
