- name: Script to start/stop all the services
  template:
    src: templates/control-all-the-things.j2
    dest: /usr/local/bin/{{ item }}-all-the-things
    mode: 0755
  with_items:
  - stop
  - start

- name: Desktop file to follow the cut list
  template:
    src: templates/videoteam-cutlist.desktop.j2
    dest: /usr/share/applications/videoteam-cutlist.desktop

- name: Script to move video to the server
  template:
    src: templates/videoteam-copy-recordings.j2
    dest: /usr/local/bin/videoteam-copy-recordings
    mode: 0755
