- name: Script to start/stop all the services
  template:
    src: templates/control-all-the-things.j2
    dest: /usr/bin/{{ item }}-all-the-things
    mode: 0755
  with_items:
  - stop
  - start

- name: Desktop File to follow the cut list
  template:
    src: templates/videoteam-cutlist.desktop.j2
    dest: /usr/share/applications/videoteam-cutlist.desktop
