---
- name: Format video partition
  filesystem:
    fstype: ext4
    dev: "{{ video_disk }}"
  failed_when: false
  # failed_when: ''is already used' not in results"
  #   "msg": "'/dev/sdb1' is already used as ext2, use force=yes to overwrite",

- name: Create video partition mountpoint
  file:
    path: /srv/video
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    recurse: true

- name: Configure video partition
  mount:
    src: "{{ video_disk }}"
    name: /srv/video
    fstype: ext4
    opts: defaults
    dump: '0'
    passno: '2'
    state: mounted
  failed_when: false
 # "msg": "Error mounting /srv/video: mount: /dev/sdb1 is already mounted or /srv/video busy\n       /dev/sdb1 is already mounted on /boot\n"
 #

- name: Configure video partition root ownership
  file:
    path: /srv/video
    state: directory
    owner: "{{ user_name }}"
