---
- name: Format video partition
  filesystem:
    fstype: ext4
    dev: "{{ video_disk }}"

- name: Create video partition mountpoint
  file:
    path: "/home/{{ user_name }}/Videos"
    state: directory
    owner: "{{ user_name }}"
    recurse: true

- name: Configure video partition
  mount:
    src: "{{ video_disk }}"
    name: "/home/{{ user_name }}/Videos"
    fstype: ext4
    opts: defaults
    dump: 0
    passno: 2
    state: mounted

- name: Configure video partition root ownership
  file:
    path: "/home/{{ user_name }}/Videos"
    state: directory
    owner: "{{ user_name }}"
