---
- name: Format video partition
  filesystem:
    fstype: ext4
    dev: "{{ video_disk }}"
    force: yes

- name: Create video partition mountpoint
  file:
    path: /srv/video
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    recurse: true

- name: Configure video partition
  mount:
    src: "{{ video_disk }}"
    name: /srv/video
    fstype: ext4
    opts: defaults
    dump: '0'
    passno: '2'
    state: mounted

- name: Configure video partition root ownership
  file:
    path: /srv/video
    state: directory
    owner: "{{ user_name }}"
