---
- name: install voctomix & related packages
  apt:
    name: "{{ item }}"
  with_items:
  - voctomix
  - voctomix-outcasts
  - gstreamer1.0-pulseaudio

# we need 0.4.2-1, which is in unstable
- name: install voctomix-outcasts from unstable for now
  apt:
    name: "{{ item }}"
  with_items:
  - voctomix-outcasts
  when: ansible_distribution == 'Debian'

- name: create voctomix config dir
  file:
    path: /etc/voctomix
    state: directory

- name: configure voctomix
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/voctomix/{{ item }}"
  with_items:
  - voctocore.ini
  - voctogui.ini

- name: create recording directory
  file:
    state: directory
    dest: /srv/video/{{ org }}/{{ show }}/dv/{{ room_name }}
    recurse: true
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: push the monitoring script
  copy:
    src: files/monitor-stdout
    dest: /usr/local/bin/monitor-stdout
    mode: 0755

- name: install voctocore systemd unit
  copy:
    src: files/systemd/videoteam-voctocore.service
    dest: /etc/systemd/user/videoteam-voctocore.service
  notify: reload-systemd

- name: Create loop directory
  file:
    path: /var/cache/voctomix/loop
    state: directory
    mode: 0775
    recurse: true

- name: Download the loop tarball
  get_url:
    url: "{{ voctomix.loop_url }}"
    dest: /var/cache/voctomix/loop.tar
  when: voctomix.loop_url is defined
  notify: Unpack the loop tarball

- name: install voctomix recording systemd units
  template:
    src: templates/videoteam-{{ item }}.service.j2
    dest: /etc/systemd/user/videoteam-{{ item }}.service
  with_items:
  - cutlist
  - record
  - loop
  notify: reload-systemd

- name: enable voctomix systemd units
  file:
    state: link
    src: "/etc/systemd/user/videoteam-{{ item }}.service"
    dest: "/home/{{ user_name }}/.config/systemd/user/xlogin.target.wants/videoteam-{{ item }}.service"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_items:
  - cutlist
  - record
  - voctocore
  - loop
