---
- name: install voctomix & related packages
  apt:
    name: "{{ item }}"
  with_items:
  - voctomix
  - voctomix-outcasts
  - gstreamer1.0-pulseaudio

# sane sponsor loops require voctomix-outcasts >= 0.4.2-1
- name: install voctomix-outcasts from backports
  apt:
    name: "{{ item }}"
    default_release: "{{ debian_version }}-backports"
    state: latest
  with_items:
  - voctomix
  - voctomix-core
  - voctomix-gui
  - voctomix-outcasts
  when: ansible_distribution == 'Debian'

- name: create voctomix config dir
  file:
    path: /etc/voctomix
    state: directory

- name: configure voctomix
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/voctomix/{{ item }}"
  with_items:
  - voctocore.ini
  - voctogui.ini

- name: create recording directory
  file:
    state: directory
    dest: /srv/video/{{ org }}/{{ show }}/dv/{{ room_name }}
    recurse: true
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: push the monitoring script
  copy:
    src: files/monitor-stdout
    dest: /usr/local/bin/monitor-stdout
    mode: 0755

- name: install voctocore systemd unit
  copy:
    src: files/systemd/videoteam-voctocore.service
    dest: /etc/systemd/user/videoteam-voctocore.service
  notify: reload-systemd

- name: Create loop directory
  file:
    path: /var/cache/voctomix
    state: directory
    mode: 0775

- name: Download the sponsor loop
  get_url:
    url: "{{ voctomix.loop_url }}"
    dest: /var/cache/voctomix/loop.ts
  when: voctomix.loop_url is defined

- name: Remove the sponsor loop
  file:
    path: /var/cache/voctomix/loop.ts
    state: absent
  when: voctomix.loop_url is undefined

- name: Download the background loop
  get_url:
    url: "{{ voctomix.bgloop_url }}"
    dest: /var/cache/voctomix/bgloop.ts
  when: voctomix.bgloop_url is defined

- name: Remove the background loop
  file:
    path: /var/cache/voctomix/bgloop.ts
    state: absent
  when: voctomix.bgloop_url is undefined

- name: install voctomix recording systemd units
  template:
    src: templates/videoteam-{{ item }}.service.j2
    dest: /etc/systemd/user/videoteam-{{ item }}.service
  with_items:
  - cutlist
  - record
  - loop
  - bgloop
  notify: reload-systemd

- name: enable voctomix systemd units
  file:
    state: link
    src: "/etc/systemd/user/videoteam-{{ item }}.service"
    dest: "/home/{{ user_name }}/.config/systemd/user/xlogin.target.wants/videoteam-{{ item }}.service"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_items:
  - cutlist
  - record
  - voctocore
  - loop
  - bgloop

- name: Autostart voctogui
  file:
    src: /usr/share/applications/voctogui.desktop
    dest: /etc/xdg/autostart/voctogui.desktop
    state: link

- name: Autostart record watch
  template:
    src: templates/recordwatch.desktop.j2
    dest: /etc/xdg/autostart/recordwatch.desktop
    mode: 0755
