---
- name: install voctomix & related packages
  apt:
    name: "{{ item }}"
  with_items:
  - voctomix
  - voctomix-outcasts

- name: create voctomix config dir
  file:
    path: /etc/voctomix
    state: directory

- name: configure voctomix
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/voctomix/{{ item }}"
  with_items:
  - voctocore.ini
  - voctogui.ini

- name: push the monitoring script
  copy:
    src: files/monitor-stdout
    dest: /usr/local/bin/monitor-stdout
    mode: 0755

- name: push the cutlist script
  copy:
    src: files/wrap-generate-cutlist
    dest: /usr/local/bin/wrap-generate-cutlist
    mode: 0755

- name: install voctomix systemd units
  copy:
    src: "files/systemd/videoteam-{{ item }}.service"
    dest: /etc/systemd/user/
  with_items:
  - cutlist
  - record
  - voctocore
  notify: reload-systemd

- name: enable voctomix systemd units
  file:
    state: link
    src: "/etc/systemd/user/videoteam-{{ item }}.service"
    dest: "/home/{{ user_name }}/.config/systemd/user/default.target.wants/videoteam-{{ item }}.service"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  with_items:
  - cutlist
  - record
  - voctocore
