---
- name: YouTube streaming script
  template:
    src: templates/videoteam-stream.j2
    dest: /usr/local/bin/videoteam-stream
    mode: 0755

- name: YouTube streaming systemd service
  copy:
    src: files/systemd/videoteam-stream.service
    dest: /etc/systemd/user/videoteam-stream.service
  notify: reload-systemd

- name: Enable YouTube streaming service
  file:
    state: link
    src: /etc/systemd/user/videoteam-stream.service
    dest: "/home/{{ user_name }}/.config/systemd/user/default.target.wants/videoteam-stream.service"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
