#!/bin/sh

systemctl --user import-environment DISPLAY XAUTHORITY
if which dbus-update-activation-environment >/dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi

systemctl --user start xlogin.target

lightdm-session

systemctl --user start xlogout.target
killall pulseaudio
killall gpg-agent
